services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: onai-pharma-frontend:dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
      