name: CI/CD - Test, Build, and Push to Docker Hub

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # This job runs tests and builds the application
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Using Node.js v18 to match your Dockerfile
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Application
        # This will use the "build" script from your package.json, which should
        # correspond to `ng build --configuration production` for an Angular app.
        run: npm run build

  # This job builds and pushes the Docker image to Docker Hub
  # It only runs on a push to the main branch, after the test_and_build job succeeds
  build_and_push_docker:
    # This job depends on the test_and_build job finishing successfully
    needs: test_and_build
    # Only run this job on a push to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # The context is the root of your repository, where the Dockerfile is located
          context: .
          push: true
          # The image will be tagged with your Docker Hub username and repo name
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onai-pharma-frontend:latest
